CREATE TABLE notafiscal_produtos (
    ID INT(11) NOT NULL,
    ID_NF INT(11) NOT NULL,
    ID_ITEM INT(11) NOT NULL,
    COD_PROD INT(11) NOT NULL,
    VALOR_UNIT FLOAT NOT NULL,
    QUANTIDADE INT(11) NOT NULL,
    DESCONTO INT(3) NULL,
)

INSERT INTO notafiscal_produtos (ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES
(1,1,1,25,10,5),
(1,2,2,13.5,3,NULL),
(1,3,3,15,2,NULL),
(1,4,4,10,1,NULL),
(1,5,5,30,1,NULL),
(2,1,3,15,4,NULL),
(2,2,4,10,5,NULL),
(2,3,5,30,7,NULL),
(3,1,1,25,5,NULL),
(3,2,4,10,4,NULL),
(3,3,5,30,5,NULL),
(3,4,2,13.5,7,NULL),
(4,1,5,30,10,15),
(4,2,4,10,12,5),
(4,3,1,25,13,5),
(4,4,2,13.5,15,5),
(5,1,3,15,3,NULL),
(5,2,5,30,6,NULL),
(6,1,1,25,22,15),
(6,2,3,15,25,20),
(7,1,1,25,10,3),
(7,2,2,13.5,10,4),
(7,3,3,15,10,4),
(7,4,5,30,10,1);

-- A) 

SELECT ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT FROM notafiscal_produtos WHERE DESCONTO = NULL;

-- B) SELECT 

SELECT ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, VALOR_UNIT - (VALOR_UNIT*(DESCONTO/100)) FROM notafiscal_produtos WHERE DESCONTO <> NULL;

-- C)

UPDATE notafiscal_produtos SET DESCONTO = 0 WHERE DESCONTO = NULL;

-- D)

SELECT ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, VALOR_TOTAL, DESCONTO, QUANTIDADE * VALOR_UNIT, VALOR_UNIT - (VALOR_UNIT*(DESCONTO/100)) FROM notafiscal_produtos;

-- E)

SELECT ID_NF, SUM(QUANTIDADE * VALOR_UNIT) AS VALOR_TOTAL FROM notafiscal_produtos GROUP BY ID_NF;

-- F) 

SELECT ID_NF, SUM(VALOR_UNIT - (VALOR_UNIT*(DESCONTO/100))) AS VALOR_VENDIDO GROUP BY ID_NF ORDER BY (QUANTIDADE * VALOR_UNIT) ASC;

-- G)

SELECT COD_PROD, QUANTIDADE ORDER BY QUANTIDADE DESC;

-- H) 

SELECT ID_NF, COD_PROD, QUANTIDADE ORDER BY QUANTIDADE DESC GROUP BY ID_NF WHERE QUANTIDADE > 10;

-- I)

SELECT ID_NF, SUM(QUANTIDADE * VALOR_UNIT) AS VALOR_TOTAL WHERE VALOR_TOTAL > 500 FROM notafiscal_produtos GROUP BY ID_NF;

-- J)

SELECT COD_PROD,  AVG(DESCONTO) AS MEDIA GROUP BY COD_PROD FROM notafiscal_produtos;

-- K)

COD_PROD, MIN(DESCONTO) AS MENOR, MAX(DESCONTO) AS MAIOR, AVG(DESCONTO) AS MEDIA GROUP BY COD_PROD FROM notafiscal_produtos;

-- L)

SELECT ID_NF, QTD_ITENS WHERE ROWS(ID_NF) > 3 GROUP BY ID_NF;
